"""Curated content seeds for the dashboard.

Kept as plain Python dicts/lists so the tool has no JSON loading overhead.
All LeetCode links, NeetCode/Striver/etc. resources, and process notes are
real — but mark anything you haven't personally re-verified as such in the UI.
"""
from __future__ import annotations

DSA_PATTERNS: list[dict] = [
    {
        "name": "Real-Asked / MAANG-style",
        "blurb": "Start here. Includes problems candidates have actually faced recently — including the 'blind robot' (LC489) — plus grid/maze cousins.",
        "starred": True,
        "problems": [
            {"lc": 489, "name": "Robot Room Cleaner", "diff": "Hard",
             "approach": "Backtracking with relative direction + visited set. Walk forward; if blocked, turn right. After exploring 4 directions, undo the move (go back, turn 180, go back, turn 180).",
             "code": "def cleanRoom(robot):\n    visited = set()\n    DIRS = [(-1,0),(0,1),(1,0),(0,-1)]\n    def go_back():\n        robot.turnRight(); robot.turnRight()\n        robot.move()\n        robot.turnRight(); robot.turnRight()\n    def dfs(r, c, d):\n        visited.add((r, c))\n        robot.clean()\n        for i in range(4):\n            nd = (d + i) % 4\n            nr, nc = r + DIRS[nd][0], c + DIRS[nd][1]\n            if (nr, nc) not in visited and robot.move():\n                dfs(nr, nc, nd)\n                go_back()\n            robot.turnRight()\n    dfs(0, 0, 0)",
             "time": "O(N - obstacles)", "space": "O(N)",
             "url": "https://leetcode.com/problems/robot-room-cleaner/"},
            {"lc": 1091, "name": "Shortest Path in Binary Matrix", "diff": "Medium",
             "approach": "BFS from (0,0). 8 directions. Track distance.",
             "code": "from collections import deque\ndef shortestPathBinaryMatrix(grid):\n    n = len(grid)\n    if grid[0][0] or grid[n-1][n-1]: return -1\n    DIRS = [(-1,-1),(-1,0),(-1,1),(0,-1),(0,1),(1,-1),(1,0),(1,1)]\n    q = deque([(0, 0, 1)])\n    grid[0][0] = 1  # visited\n    while q:\n        r, c, d = q.popleft()\n        if r == n-1 and c == n-1: return d\n        for dr, dc in DIRS:\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < n and 0 <= nc < n and grid[nr][nc] == 0:\n                grid[nr][nc] = 1\n                q.append((nr, nc, d+1))\n    return -1",
             "time": "O(N^2)", "space": "O(N^2)",
             "url": "https://leetcode.com/problems/shortest-path-in-binary-matrix/"},
            {"lc": 200, "name": "Number of Islands", "diff": "Medium",
             "approach": "DFS or BFS flood-fill; count starts.",
             "code": "def numIslands(grid):\n    if not grid: return 0\n    rows, cols = len(grid), len(grid[0])\n    def dfs(r, c):\n        if r < 0 or r >= rows or c < 0 or c >= cols or grid[r][c] != '1': return\n        grid[r][c] = '0'\n        dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == '1':\n                dfs(r, c); count += 1\n    return count",
             "time": "O(R*C)", "space": "O(R*C)",
             "url": "https://leetcode.com/problems/number-of-islands/"},
            {"lc": 994, "name": "Rotting Oranges", "diff": "Medium",
             "approach": "Multi-source BFS from all rotten cells; track minutes.",
             "code": "from collections import deque\ndef orangesRotting(grid):\n    rows, cols = len(grid), len(grid[0])\n    q = deque(); fresh = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 2: q.append((r, c, 0))\n            elif grid[r][c] == 1: fresh += 1\n    minutes = 0\n    while q:\n        r, c, m = q.popleft()\n        minutes = max(minutes, m)\n        for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 1:\n                grid[nr][nc] = 2; fresh -= 1\n                q.append((nr, nc, m+1))\n    return minutes if fresh == 0 else -1",
             "time": "O(R*C)", "space": "O(R*C)",
             "url": "https://leetcode.com/problems/rotting-oranges/"},
        ],
    },
    {
        "name": "Arrays & Hashing",
        "blurb": "Bread and butter. Lookups, counts, set membership.",
        "problems": [
            {"lc": 1, "name": "Two Sum", "diff": "Easy",
             "approach": "Hashmap of value → index; check complement.",
             "code": "def twoSum(nums, target):\n    seen = {}\n    for i, x in enumerate(nums):\n        if target - x in seen:\n            return [seen[target - x], i]\n        seen[x] = i",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/two-sum/"},
            {"lc": 49, "name": "Group Anagrams", "diff": "Medium",
             "approach": "Key each string by sorted chars (or 26-letter tuple).",
             "code": "from collections import defaultdict\ndef groupAnagrams(strs):\n    groups = defaultdict(list)\n    for s in strs:\n        groups[tuple(sorted(s))].append(s)\n    return list(groups.values())",
             "time": "O(n*k log k)", "space": "O(n*k)",
             "url": "https://leetcode.com/problems/group-anagrams/"},
            {"lc": 347, "name": "Top K Frequent Elements", "diff": "Medium",
             "approach": "Counter + bucket sort by frequency.",
             "code": "from collections import Counter\ndef topKFrequent(nums, k):\n    counts = Counter(nums)\n    buckets = [[] for _ in range(len(nums) + 1)]\n    for n, c in counts.items():\n        buckets[c].append(n)\n    out = []\n    for c in range(len(buckets) - 1, 0, -1):\n        out.extend(buckets[c])\n        if len(out) >= k:\n            return out[:k]\n    return out",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/top-k-frequent-elements/"},
            {"lc": 128, "name": "Longest Consecutive Sequence", "diff": "Medium",
             "approach": "Set; only start counting from sequence starts (n-1 not in set).",
             "code": "def longestConsecutive(nums):\n    s = set(nums); best = 0\n    for n in s:\n        if n - 1 not in s:\n            cur = n; length = 1\n            while cur + 1 in s:\n                cur += 1; length += 1\n            best = max(best, length)\n    return best",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/longest-consecutive-sequence/"},
            {"lc": 238, "name": "Product of Array Except Self", "diff": "Medium",
             "approach": "Prefix products from left, then sweep right multiplying suffix.",
             "code": "def productExceptSelf(nums):\n    n = len(nums); out = [1] * n\n    left = 1\n    for i in range(n):\n        out[i] = left; left *= nums[i]\n    right = 1\n    for i in range(n - 1, -1, -1):\n        out[i] *= right; right *= nums[i]\n    return out",
             "time": "O(n)", "space": "O(1) extra",
             "url": "https://leetcode.com/problems/product-of-array-except-self/"},
            {"lc": 217, "name": "Contains Duplicate", "diff": "Easy",
             "approach": "Set membership check.",
             "code": "def containsDuplicate(nums):\n    s = set()\n    for x in nums:\n        if x in s: return True\n        s.add(x)\n    return False",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/contains-duplicate/"},
            {"lc": 242, "name": "Valid Anagram", "diff": "Easy",
             "approach": "Counter equality (or sort).",
             "code": "from collections import Counter\ndef isAnagram(s, t):\n    return Counter(s) == Counter(t)",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/valid-anagram/"},
        ],
    },
    {
        "name": "Two Pointers",
        "blurb": "Sorted arrays, palindromes, 3Sum-style.",
        "problems": [
            {"lc": 125, "name": "Valid Palindrome", "diff": "Easy",
             "approach": "Lowercase + skip non-alnum; converging pointers.",
             "code": "def isPalindrome(s):\n    i, j = 0, len(s) - 1\n    while i < j:\n        while i < j and not s[i].isalnum(): i += 1\n        while i < j and not s[j].isalnum(): j -= 1\n        if s[i].lower() != s[j].lower(): return False\n        i += 1; j -= 1\n    return True",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/valid-palindrome/"},
            {"lc": 15, "name": "3Sum", "diff": "Medium",
             "approach": "Sort; fix i; two-pointer j,k for the rest. Skip duplicates.",
             "code": "def threeSum(nums):\n    nums.sort(); out = []\n    for i in range(len(nums) - 2):\n        if i and nums[i] == nums[i-1]: continue\n        j, k = i + 1, len(nums) - 1\n        while j < k:\n            s = nums[i] + nums[j] + nums[k]\n            if s == 0:\n                out.append([nums[i], nums[j], nums[k]])\n                j += 1; k -= 1\n                while j < k and nums[j] == nums[j-1]: j += 1\n                while j < k and nums[k] == nums[k+1]: k -= 1\n            elif s < 0: j += 1\n            else: k -= 1\n    return out",
             "time": "O(n^2)", "space": "O(1)",
             "url": "https://leetcode.com/problems/3sum/"},
            {"lc": 11, "name": "Container With Most Water", "diff": "Medium",
             "approach": "Converging pointers; move the shorter side.",
             "code": "def maxArea(height):\n    i, j = 0, len(height) - 1\n    best = 0\n    while i < j:\n        best = max(best, (j - i) * min(height[i], height[j]))\n        if height[i] < height[j]: i += 1\n        else: j -= 1\n    return best",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/container-with-most-water/"},
            {"lc": 42, "name": "Trapping Rain Water", "diff": "Hard",
             "approach": "Two pointers; track left/right max as you converge.",
             "code": "def trap(h):\n    i, j = 0, len(h) - 1\n    lmax = rmax = total = 0\n    while i < j:\n        if h[i] < h[j]:\n            if h[i] >= lmax: lmax = h[i]\n            else: total += lmax - h[i]\n            i += 1\n        else:\n            if h[j] >= rmax: rmax = h[j]\n            else: total += rmax - h[j]\n            j -= 1\n    return total",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/trapping-rain-water/"},
        ],
    },
    {
        "name": "Sliding Window",
        "blurb": "Subarrays / substrings with monotonic constraints.",
        "problems": [
            {"lc": 3, "name": "Longest Substring Without Repeating Characters", "diff": "Medium",
             "approach": "Expand right, last-seen map, jump left when dup.",
             "code": "def lengthOfLongestSubstring(s):\n    last = {}; left = 0; best = 0\n    for r, ch in enumerate(s):\n        if ch in last and last[ch] >= left:\n            left = last[ch] + 1\n        last[ch] = r\n        best = max(best, r - left + 1)\n    return best",
             "time": "O(n)", "space": "O(k)",
             "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/"},
            {"lc": 76, "name": "Minimum Window Substring", "diff": "Hard",
             "approach": "Need/have counters; expand right until all matched, shrink left for best window.",
             "code": "from collections import Counter\ndef minWindow(s, t):\n    if not t or not s: return ''\n    need = Counter(t); missing = len(t)\n    left = best_left = best_right = 0; best = float('inf')\n    for r, ch in enumerate(s):\n        if need[ch] > 0: missing -= 1\n        need[ch] -= 1\n        while missing == 0:\n            if r - left + 1 < best:\n                best = r - left + 1; best_left, best_right = left, r + 1\n            need[s[left]] += 1\n            if need[s[left]] > 0: missing += 1\n            left += 1\n    return s[best_left:best_right] if best < float('inf') else ''",
             "time": "O(n)", "space": "O(k)",
             "url": "https://leetcode.com/problems/minimum-window-substring/"},
            {"lc": 424, "name": "Longest Repeating Character Replacement", "diff": "Medium",
             "approach": "Track max-freq in window; when (window - maxFreq) > k, shrink.",
             "code": "def characterReplacement(s, k):\n    counts = {}; left = best = maxf = 0\n    for r, ch in enumerate(s):\n        counts[ch] = counts.get(ch, 0) + 1\n        maxf = max(maxf, counts[ch])\n        if (r - left + 1) - maxf > k:\n            counts[s[left]] -= 1; left += 1\n        best = max(best, r - left + 1)\n    return best",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/longest-repeating-character-replacement/"},
            {"lc": 121, "name": "Best Time to Buy and Sell Stock", "diff": "Easy",
             "approach": "Track min-so-far + best profit.",
             "code": "def maxProfit(prices):\n    mn = float('inf'); best = 0\n    for p in prices:\n        if p < mn: mn = p\n        else: best = max(best, p - mn)\n    return best",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"},
            {"lc": 567, "name": "Permutation in String", "diff": "Medium",
             "approach": "Fixed-window char counter equality.",
             "code": "from collections import Counter\ndef checkInclusion(s1, s2):\n    if len(s1) > len(s2): return False\n    need = Counter(s1); have = Counter(s2[:len(s1)])\n    if need == have: return True\n    for i in range(len(s1), len(s2)):\n        have[s2[i]] += 1\n        have[s2[i - len(s1)]] -= 1\n        if have[s2[i - len(s1)]] == 0: del have[s2[i - len(s1)]]\n        if need == have: return True\n    return False",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/permutation-in-string/"},
        ],
    },
    {
        "name": "Stack",
        "blurb": "LIFO problems, monotonic stacks, parsing.",
        "problems": [
            {"lc": 20, "name": "Valid Parentheses", "diff": "Easy",
             "approach": "Push opens; on close, top must match.",
             "code": "def isValid(s):\n    pairs = {')':'(', ']':'[', '}':'{'}\n    stack = []\n    for ch in s:\n        if ch in pairs:\n            if not stack or stack.pop() != pairs[ch]: return False\n        else:\n            stack.append(ch)\n    return not stack",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/valid-parentheses/"},
            {"lc": 739, "name": "Daily Temperatures", "diff": "Medium",
             "approach": "Monotonic decreasing stack of indices.",
             "code": "def dailyTemperatures(t):\n    out = [0] * len(t); stack = []\n    for i, x in enumerate(t):\n        while stack and t[stack[-1]] < x:\n            j = stack.pop(); out[j] = i - j\n        stack.append(i)\n    return out",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/daily-temperatures/"},
            {"lc": 84, "name": "Largest Rectangle in Histogram", "diff": "Hard",
             "approach": "Monotonic increasing stack; pop on smaller bar to compute area.",
             "code": "def largestRectangleArea(h):\n    stack = []; best = 0\n    for i, x in enumerate(h + [0]):\n        while stack and h[stack[-1]] > x:\n            top = stack.pop()\n            width = i if not stack else i - stack[-1] - 1\n            best = max(best, h[top] * width)\n        stack.append(i)\n    return best",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/"},
            {"lc": 155, "name": "Min Stack", "diff": "Medium",
             "approach": "Auxiliary stack of running minimums.",
             "code": "class MinStack:\n    def __init__(self): self.s = []; self.m = []\n    def push(self, x):\n        self.s.append(x)\n        self.m.append(x if not self.m else min(x, self.m[-1]))\n    def pop(self): self.s.pop(); self.m.pop()\n    def top(self): return self.s[-1]\n    def getMin(self): return self.m[-1]",
             "time": "O(1) per op", "space": "O(n)",
             "url": "https://leetcode.com/problems/min-stack/"},
        ],
    },
    {
        "name": "Binary Search",
        "blurb": "Sorted arrays, rotated arrays, search on answer.",
        "problems": [
            {"lc": 704, "name": "Binary Search", "diff": "Easy",
             "approach": "Classic lo/hi.",
             "code": "def search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target: return mid\n        if nums[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1",
             "time": "O(log n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/binary-search/"},
            {"lc": 33, "name": "Search in Rotated Sorted Array", "diff": "Medium",
             "approach": "Decide which half is sorted; recurse on the side that contains target.",
             "code": "def search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target: return mid\n        if nums[lo] <= nums[mid]:\n            if nums[lo] <= target < nums[mid]: hi = mid - 1\n            else: lo = mid + 1\n        else:\n            if nums[mid] < target <= nums[hi]: lo = mid + 1\n            else: hi = mid - 1\n    return -1",
             "time": "O(log n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/"},
            {"lc": 875, "name": "Koko Eating Bananas", "diff": "Medium",
             "approach": "Binary search on speed; feasibility check.",
             "code": "import math\ndef minEatingSpeed(piles, h):\n    lo, hi = 1, max(piles)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if sum(math.ceil(p/mid) for p in piles) <= h: hi = mid\n        else: lo = mid + 1\n    return lo",
             "time": "O(n log max)", "space": "O(1)",
             "url": "https://leetcode.com/problems/koko-eating-bananas/"},
            {"lc": 34, "name": "Find First and Last Position", "diff": "Medium",
             "approach": "Two binary searches: leftmost and rightmost.",
             "code": "from bisect import bisect_left, bisect_right\ndef searchRange(nums, target):\n    l = bisect_left(nums, target)\n    r = bisect_right(nums, target) - 1\n    if l <= r and l < len(nums) and nums[l] == target: return [l, r]\n    return [-1, -1]",
             "time": "O(log n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/"},
            {"lc": 153, "name": "Find Minimum in Rotated Sorted Array", "diff": "Medium",
             "approach": "Binary search with rotation invariant.",
             "code": "def findMin(nums):\n    lo, hi = 0, len(nums) - 1\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] > nums[hi]: lo = mid + 1\n        else: hi = mid\n    return nums[lo]",
             "time": "O(log n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"},
        ],
    },
    {
        "name": "Linked List",
        "blurb": "Pointers, dummies, runners. Includes the brutal ones.",
        "problems": [
            {"lc": 206, "name": "Reverse Linked List", "diff": "Easy",
             "approach": "Iterative prev/cur/next.",
             "code": "def reverseList(head):\n    prev = None; cur = head\n    while cur:\n        nxt = cur.next; cur.next = prev; prev = cur; cur = nxt\n    return prev",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/reverse-linked-list/"},
            {"lc": 21, "name": "Merge Two Sorted Lists", "diff": "Easy",
             "approach": "Dummy + pick smaller head.",
             "code": "def mergeTwoLists(a, b):\n    from collections import namedtuple\n    class N: pass\n    dummy = N(); dummy.next = None; tail = dummy\n    while a and b:\n        if a.val <= b.val: tail.next = a; a = a.next\n        else: tail.next = b; b = b.next\n        tail = tail.next\n    tail.next = a or b\n    return dummy.next",
             "time": "O(n+m)", "space": "O(1)",
             "url": "https://leetcode.com/problems/merge-two-sorted-lists/"},
            {"lc": 23, "name": "Merge k Sorted Lists", "diff": "Hard",
             "approach": "Min-heap of (val, idx, node).",
             "code": "import heapq\ndef mergeKLists(lists):\n    h = []\n    for i, n in enumerate(lists):\n        if n: heapq.heappush(h, (n.val, i, n))\n    class N: pass\n    dummy = N(); dummy.next = None; tail = dummy\n    while h:\n        v, i, n = heapq.heappop(h)\n        tail.next = n; tail = n\n        if n.next: heapq.heappush(h, (n.next.val, i, n.next))\n    return dummy.next",
             "time": "O(N log k)", "space": "O(k)",
             "url": "https://leetcode.com/problems/merge-k-sorted-lists/"},
            {"lc": 25, "name": "Reverse Nodes in k-Group", "diff": "Hard",
             "approach": "Walk k ahead; reverse the segment in-place; reconnect to tail.",
             "code": "def reverseKGroup(head, k):\n    class N: pass\n    dummy = N(); dummy.next = head; group_prev = dummy\n    while True:\n        kth = group_prev\n        for _ in range(k):\n            kth = kth.next\n            if not kth: return dummy.next\n        group_next = kth.next\n        prev, cur = group_next, group_prev.next\n        while cur is not group_next:\n            nxt = cur.next; cur.next = prev; prev = cur; cur = nxt\n        tmp = group_prev.next\n        group_prev.next = kth\n        group_prev = tmp",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/reverse-nodes-in-k-group/"},
            {"lc": 138, "name": "Copy List with Random Pointer", "diff": "Medium",
             "approach": "Hashmap old→new, then wire next/random.",
             "code": "def copyRandomList(head):\n    if not head: return None\n    mp = {}\n    cur = head\n    while cur:\n        class N: pass\n        n = N(); n.val = cur.val; n.next = None; n.random = None\n        mp[cur] = n; cur = cur.next\n    cur = head\n    while cur:\n        mp[cur].next = mp.get(cur.next)\n        mp[cur].random = mp.get(cur.random)\n        cur = cur.next\n    return mp[head]",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/copy-list-with-random-pointer/"},
        ],
    },
    {
        "name": "Trees",
        "blurb": "Traversal, recursion, BST invariants.",
        "problems": [
            {"lc": 104, "name": "Maximum Depth of Binary Tree", "diff": "Easy",
             "approach": "1 + max(left, right).",
             "code": "def maxDepth(root):\n    if not root: return 0\n    return 1 + max(maxDepth(root.left), maxDepth(root.right))",
             "time": "O(n)", "space": "O(h)",
             "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/"},
            {"lc": 102, "name": "Binary Tree Level Order Traversal", "diff": "Medium",
             "approach": "BFS with a deque.",
             "code": "from collections import deque\ndef levelOrder(root):\n    if not root: return []\n    out = []; q = deque([root])\n    while q:\n        level = []\n        for _ in range(len(q)):\n            n = q.popleft(); level.append(n.val)\n            if n.left: q.append(n.left)\n            if n.right: q.append(n.right)\n        out.append(level)\n    return out",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/"},
            {"lc": 124, "name": "Binary Tree Maximum Path Sum", "diff": "Hard",
             "approach": "Post-order; left/right gains (clamp at 0); update global with through-node sum.",
             "code": "def maxPathSum(root):\n    best = float('-inf')\n    def gain(n):\n        nonlocal best\n        if not n: return 0\n        l = max(gain(n.left), 0)\n        r = max(gain(n.right), 0)\n        best = max(best, n.val + l + r)\n        return n.val + max(l, r)\n    gain(root)\n    return best",
             "time": "O(n)", "space": "O(h)",
             "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/"},
            {"lc": 98, "name": "Validate BST", "diff": "Medium",
             "approach": "Pass low/high bounds down.",
             "code": "def isValidBST(root, lo=float('-inf'), hi=float('inf')):\n    if not root: return True\n    if not lo < root.val < hi: return False\n    return isValidBST(root.left, lo, root.val) and isValidBST(root.right, root.val, hi)",
             "time": "O(n)", "space": "O(h)",
             "url": "https://leetcode.com/problems/validate-binary-search-tree/"},
            {"lc": 226, "name": "Invert Binary Tree", "diff": "Easy",
             "approach": "Swap children, recurse.",
             "code": "def invertTree(root):\n    if not root: return None\n    root.left, root.right = invertTree(root.right), invertTree(root.left)\n    return root",
             "time": "O(n)", "space": "O(h)",
             "url": "https://leetcode.com/problems/invert-binary-tree/"},
            {"lc": 235, "name": "Lowest Common Ancestor of BST", "diff": "Medium",
             "approach": "Walk down using BST property until split.",
             "code": "def lowestCommonAncestor(root, p, q):\n    while root:\n        if p.val < root.val and q.val < root.val: root = root.left\n        elif p.val > root.val and q.val > root.val: root = root.right\n        else: return root",
             "time": "O(h)", "space": "O(1)",
             "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/"},
        ],
    },
    {
        "name": "Heap / Priority Queue",
        "blurb": "Top-K, streams, scheduling.",
        "problems": [
            {"lc": 215, "name": "Kth Largest Element in Array", "diff": "Medium",
             "approach": "Min-heap of size k; or quickselect.",
             "code": "import heapq\ndef findKthLargest(nums, k):\n    h = nums[:k]\n    heapq.heapify(h)\n    for x in nums[k:]:\n        if x > h[0]:\n            heapq.heapreplace(h, x)\n    return h[0]",
             "time": "O(n log k)", "space": "O(k)",
             "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/"},
            {"lc": 295, "name": "Find Median from Data Stream", "diff": "Hard",
             "approach": "Two heaps: max-heap lower half, min-heap upper half.",
             "code": "import heapq\nclass MedianFinder:\n    def __init__(self):\n        self.lo = []; self.hi = []\n    def addNum(self, n):\n        heapq.heappush(self.lo, -heapq.heappushpop(self.hi, n))\n        if len(self.lo) > len(self.hi) + 1:\n            heapq.heappush(self.hi, -heapq.heappop(self.lo))\n    def findMedian(self):\n        if len(self.lo) > len(self.hi): return -self.lo[0]\n        return (-self.lo[0] + self.hi[0]) / 2",
             "time": "O(log n) add", "space": "O(n)",
             "url": "https://leetcode.com/problems/find-median-from-data-stream/"},
            {"lc": 621, "name": "Task Scheduler", "diff": "Medium",
             "approach": "Math: idle slots = (maxFreq - 1) * (n + 1) + count of maxFreq tasks.",
             "code": "from collections import Counter\ndef leastInterval(tasks, n):\n    c = Counter(tasks)\n    m = max(c.values()); k = sum(1 for v in c.values() if v == m)\n    return max(len(tasks), (m - 1) * (n + 1) + k)",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/task-scheduler/"},
            {"lc": 973, "name": "K Closest Points to Origin", "diff": "Medium",
             "approach": "Max-heap of size k by squared distance.",
             "code": "import heapq\ndef kClosest(points, k):\n    h = []\n    for x, y in points:\n        d = -(x*x + y*y)\n        if len(h) < k: heapq.heappush(h, (d, x, y))\n        elif d > h[0][0]: heapq.heapreplace(h, (d, x, y))\n    return [[x, y] for _, x, y in h]",
             "time": "O(n log k)", "space": "O(k)",
             "url": "https://leetcode.com/problems/k-closest-points-to-origin/"},
        ],
    },
    {
        "name": "Backtracking",
        "blurb": "Choose / explore / un-choose. Subsets, permutations, partitions.",
        "problems": [
            {"lc": 78, "name": "Subsets", "diff": "Medium",
             "approach": "Include/exclude at each index.",
             "code": "def subsets(nums):\n    out = []; cur = []\n    def bt(i):\n        if i == len(nums):\n            out.append(cur[:]); return\n        cur.append(nums[i]); bt(i+1); cur.pop()\n        bt(i+1)\n    bt(0); return out",
             "time": "O(2^n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/subsets/"},
            {"lc": 46, "name": "Permutations", "diff": "Medium",
             "approach": "Swap-in-place or used-set.",
             "code": "def permute(nums):\n    out = []\n    def bt(i):\n        if i == len(nums):\n            out.append(nums[:]); return\n        for j in range(i, len(nums)):\n            nums[i], nums[j] = nums[j], nums[i]\n            bt(i+1)\n            nums[i], nums[j] = nums[j], nums[i]\n    bt(0); return out",
             "time": "O(n*n!)", "space": "O(n)",
             "url": "https://leetcode.com/problems/permutations/"},
            {"lc": 79, "name": "Word Search", "diff": "Medium",
             "approach": "DFS from each cell; mark visited via temp char swap.",
             "code": "def exist(board, word):\n    R, C = len(board), len(board[0])\n    def dfs(r, c, i):\n        if i == len(word): return True\n        if r < 0 or r >= R or c < 0 or c >= C or board[r][c] != word[i]: return False\n        tmp = board[r][c]; board[r][c] = '#'\n        ok = dfs(r+1,c,i+1) or dfs(r-1,c,i+1) or dfs(r,c+1,i+1) or dfs(r,c-1,i+1)\n        board[r][c] = tmp\n        return ok\n    for r in range(R):\n        for c in range(C):\n            if dfs(r, c, 0): return True\n    return False",
             "time": "O(R*C*4^L)", "space": "O(L)",
             "url": "https://leetcode.com/problems/word-search/"},
            {"lc": 39, "name": "Combination Sum", "diff": "Medium",
             "approach": "DFS choose-with-replacement; index marches forward to avoid dupes.",
             "code": "def combinationSum(c, target):\n    c.sort(); out = []; cur = []\n    def bt(i, rem):\n        if rem == 0: out.append(cur[:]); return\n        for j in range(i, len(c)):\n            if c[j] > rem: break\n            cur.append(c[j]); bt(j, rem - c[j]); cur.pop()\n    bt(0, target); return out",
             "time": "O(2^t)", "space": "O(t)",
             "url": "https://leetcode.com/problems/combination-sum/"},
            {"lc": 51, "name": "N-Queens", "diff": "Hard",
             "approach": "Backtrack column by column; track cols + two diagonals.",
             "code": "def solveNQueens(n):\n    out = []; cols=set(); d1=set(); d2=set(); board=[['.']*n for _ in range(n)]\n    def bt(r):\n        if r == n: out.append([''.join(row) for row in board]); return\n        for c in range(n):\n            if c in cols or (r-c) in d1 or (r+c) in d2: continue\n            cols.add(c); d1.add(r-c); d2.add(r+c); board[r][c]='Q'\n            bt(r+1)\n            cols.remove(c); d1.remove(r-c); d2.remove(r+c); board[r][c]='.'\n    bt(0); return out",
             "time": "O(n!)", "space": "O(n)",
             "url": "https://leetcode.com/problems/n-queens/"},
        ],
    },
    {
        "name": "Graphs",
        "blurb": "BFS/DFS/Union-Find on adjacency lists or grids.",
        "problems": [
            {"lc": 207, "name": "Course Schedule", "diff": "Medium",
             "approach": "Topological sort via Kahn's BFS or DFS 3-color.",
             "code": "from collections import defaultdict, deque\ndef canFinish(n, pre):\n    g = defaultdict(list); indeg = [0]*n\n    for a, b in pre:\n        g[b].append(a); indeg[a] += 1\n    q = deque([i for i in range(n) if indeg[i] == 0]); taken = 0\n    while q:\n        x = q.popleft(); taken += 1\n        for y in g[x]:\n            indeg[y] -= 1\n            if indeg[y] == 0: q.append(y)\n    return taken == n",
             "time": "O(V+E)", "space": "O(V+E)",
             "url": "https://leetcode.com/problems/course-schedule/"},
            {"lc": 133, "name": "Clone Graph", "diff": "Medium",
             "approach": "DFS with memo of original→clone.",
             "code": "def cloneGraph(node):\n    if not node: return None\n    memo = {}\n    def dfs(n):\n        if n in memo: return memo[n]\n        class N: pass\n        c = N(); c.val = n.val; c.neighbors = []\n        memo[n] = c\n        for nb in n.neighbors: c.neighbors.append(dfs(nb))\n        return c\n    return dfs(node)",
             "time": "O(V+E)", "space": "O(V)",
             "url": "https://leetcode.com/problems/clone-graph/"},
            {"lc": 417, "name": "Pacific Atlantic Water Flow", "diff": "Medium",
             "approach": "BFS/DFS from each ocean inward; intersect.",
             "code": "def pacificAtlantic(h):\n    if not h: return []\n    R, C = len(h), len(h[0])\n    pac, atl = set(), set()\n    def dfs(r, c, seen):\n        seen.add((r, c))\n        for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:\n            nr, nc = r+dr, c+dc\n            if 0 <= nr < R and 0 <= nc < C and (nr, nc) not in seen and h[nr][nc] >= h[r][c]:\n                dfs(nr, nc, seen)\n    for r in range(R):\n        dfs(r, 0, pac); dfs(r, C-1, atl)\n    for c in range(C):\n        dfs(0, c, pac); dfs(R-1, c, atl)\n    return [[r, c] for r, c in pac & atl]",
             "time": "O(R*C)", "space": "O(R*C)",
             "url": "https://leetcode.com/problems/pacific-atlantic-water-flow/"},
            {"lc": 323, "name": "Number of Connected Components", "diff": "Medium",
             "approach": "Union-Find with path compression.",
             "code": "def countComponents(n, edges):\n    parent = list(range(n))\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]; x = parent[x]\n        return x\n    comp = n\n    for a, b in edges:\n        ra, rb = find(a), find(b)\n        if ra != rb: parent[ra] = rb; comp -= 1\n    return comp",
             "time": "O(E α(N))", "space": "O(N)",
             "url": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/"},
            {"lc": 127, "name": "Word Ladder", "diff": "Hard",
             "approach": "BFS over generic-pattern graph (wildcards as buckets).",
             "code": "from collections import defaultdict, deque\ndef ladderLength(begin, end, words):\n    if end not in words: return 0\n    buckets = defaultdict(list)\n    for w in words:\n        for i in range(len(w)):\n            buckets[w[:i] + '*' + w[i+1:]].append(w)\n    seen = {begin}; q = deque([(begin, 1)])\n    while q:\n        w, d = q.popleft()\n        if w == end: return d\n        for i in range(len(w)):\n            key = w[:i] + '*' + w[i+1:]\n            for nw in buckets[key]:\n                if nw not in seen:\n                    seen.add(nw); q.append((nw, d+1))\n    return 0",
             "time": "O(N*L^2)", "space": "O(N*L)",
             "url": "https://leetcode.com/problems/word-ladder/"},
        ],
    },
    {
        "name": "Advanced Graphs",
        "blurb": "Dijkstra, MST, complex traversals.",
        "problems": [
            {"lc": 743, "name": "Network Delay Time", "diff": "Medium",
             "approach": "Dijkstra from k. Answer = max distance, or -1 if unreachable.",
             "code": "import heapq\nfrom collections import defaultdict\ndef networkDelayTime(times, n, k):\n    g = defaultdict(list)\n    for u, v, w in times: g[u].append((v, w))\n    dist = {}; h = [(0, k)]\n    while h:\n        d, u = heapq.heappop(h)\n        if u in dist: continue\n        dist[u] = d\n        for v, w in g[u]:\n            if v not in dist: heapq.heappush(h, (d+w, v))\n    return max(dist.values()) if len(dist) == n else -1",
             "time": "O((V+E) log V)", "space": "O(V+E)",
             "url": "https://leetcode.com/problems/network-delay-time/"},
            {"lc": 787, "name": "Cheapest Flights Within K Stops", "diff": "Medium",
             "approach": "Bellman-Ford-style, relax k+1 times.",
             "code": "def findCheapestPrice(n, flights, src, dst, k):\n    INF = float('inf'); dist = [INF]*n; dist[src] = 0\n    for _ in range(k+1):\n        tmp = dist[:]\n        for u, v, w in flights:\n            if dist[u] + w < tmp[v]: tmp[v] = dist[u] + w\n        dist = tmp\n    return -1 if dist[dst] == INF else dist[dst]",
             "time": "O(K*E)", "space": "O(V)",
             "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/"},
            {"lc": 1584, "name": "Min Cost to Connect All Points (MST)", "diff": "Medium",
             "approach": "Prim's MST with min-heap; Manhattan distance.",
             "code": "import heapq\ndef minCostConnectPoints(points):\n    n = len(points); seen = set(); h = [(0, 0)]; total = 0\n    while len(seen) < n:\n        d, u = heapq.heappop(h)\n        if u in seen: continue\n        seen.add(u); total += d\n        ux, uy = points[u]\n        for v in range(n):\n            if v not in seen:\n                vx, vy = points[v]\n                heapq.heappush(h, (abs(ux-vx) + abs(uy-vy), v))\n    return total",
             "time": "O(n^2 log n)", "space": "O(n^2)",
             "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/"},
        ],
    },
    {
        "name": "1-D DP",
        "blurb": "Sequence DP; rolling arrays once it clicks.",
        "problems": [
            {"lc": 70, "name": "Climbing Stairs", "diff": "Easy",
             "approach": "Fibonacci.",
             "code": "def climbStairs(n):\n    a, b = 1, 1\n    for _ in range(n): a, b = b, a + b\n    return a",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/climbing-stairs/"},
            {"lc": 198, "name": "House Robber", "diff": "Medium",
             "approach": "dp[i] = max(dp[i-1], dp[i-2] + a[i]).",
             "code": "def rob(nums):\n    prev = cur = 0\n    for x in nums: prev, cur = cur, max(cur, prev + x)\n    return cur",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/house-robber/"},
            {"lc": 300, "name": "Longest Increasing Subsequence", "diff": "Medium",
             "approach": "Patience sort with bisect for O(n log n).",
             "code": "from bisect import bisect_left\ndef lengthOfLIS(nums):\n    tails = []\n    for x in nums:\n        i = bisect_left(tails, x)\n        if i == len(tails): tails.append(x)\n        else: tails[i] = x\n    return len(tails)",
             "time": "O(n log n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/longest-increasing-subsequence/"},
            {"lc": 322, "name": "Coin Change", "diff": "Medium",
             "approach": "dp[a] = min over coins of dp[a-c] + 1.",
             "code": "def coinChange(coins, amount):\n    INF = amount + 1\n    dp = [0] + [INF]*amount\n    for a in range(1, amount+1):\n        for c in coins:\n            if c <= a: dp[a] = min(dp[a], dp[a-c] + 1)\n    return dp[amount] if dp[amount] != INF else -1",
             "time": "O(n*amount)", "space": "O(amount)",
             "url": "https://leetcode.com/problems/coin-change/"},
            {"lc": 139, "name": "Word Break", "diff": "Medium",
             "approach": "dp[i] true iff some j<=i s.t. dp[j] and s[j:i] in dict.",
             "code": "def wordBreak(s, words):\n    ws = set(words); n = len(s)\n    dp = [False]*(n+1); dp[0] = True\n    for i in range(1, n+1):\n        for j in range(i):\n            if dp[j] and s[j:i] in ws:\n                dp[i] = True; break\n    return dp[n]",
             "time": "O(n^2)", "space": "O(n)",
             "url": "https://leetcode.com/problems/word-break/"},
        ],
    },
    {
        "name": "2-D DP",
        "blurb": "Grids, edit distance, LCS.",
        "problems": [
            {"lc": 1143, "name": "Longest Common Subsequence", "diff": "Medium",
             "approach": "2D DP table; rolling array possible.",
             "code": "def longestCommonSubsequence(a, b):\n    m, n = len(a), len(b)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(m):\n        for j in range(n):\n            if a[i] == b[j]: dp[i+1][j+1] = dp[i][j] + 1\n            else: dp[i+1][j+1] = max(dp[i+1][j], dp[i][j+1])\n    return dp[m][n]",
             "time": "O(mn)", "space": "O(mn)",
             "url": "https://leetcode.com/problems/longest-common-subsequence/"},
            {"lc": 72, "name": "Edit Distance", "diff": "Medium",
             "approach": "Classic Levenshtein DP.",
             "code": "def minDistance(a, b):\n    m, n = len(a), len(b)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0] = i\n    for j in range(n+1): dp[0][j] = j\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if a[i-1] == b[j-1]: dp[i][j] = dp[i-1][j-1]\n            else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n    return dp[m][n]",
             "time": "O(mn)", "space": "O(mn)",
             "url": "https://leetcode.com/problems/edit-distance/"},
            {"lc": 62, "name": "Unique Paths", "diff": "Medium",
             "approach": "Rolling 1-D DP across rows.",
             "code": "def uniquePaths(m, n):\n    row = [1]*n\n    for _ in range(m - 1):\n        for j in range(1, n): row[j] += row[j-1]\n    return row[-1]",
             "time": "O(mn)", "space": "O(n)",
             "url": "https://leetcode.com/problems/unique-paths/"},
        ],
    },
    {
        "name": "Intervals",
        "blurb": "Sort + sweep.",
        "problems": [
            {"lc": 56, "name": "Merge Intervals", "diff": "Medium",
             "approach": "Sort by start; merge overlapping.",
             "code": "def merge(intervals):\n    intervals.sort()\n    out = []\n    for s, e in intervals:\n        if out and s <= out[-1][1]: out[-1][1] = max(out[-1][1], e)\n        else: out.append([s, e])\n    return out",
             "time": "O(n log n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/merge-intervals/"},
            {"lc": 253, "name": "Meeting Rooms II", "diff": "Medium",
             "approach": "Min-heap of end times; or two sorted arrays sweep.",
             "code": "import heapq\ndef minMeetingRooms(intervals):\n    if not intervals: return 0\n    intervals.sort()\n    h = [intervals[0][1]]\n    for s, e in intervals[1:]:\n        if h[0] <= s: heapq.heappop(h)\n        heapq.heappush(h, e)\n    return len(h)",
             "time": "O(n log n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/meeting-rooms-ii/"},
            {"lc": 57, "name": "Insert Interval", "diff": "Medium",
             "approach": "Append non-overlapping then merge the overlap region.",
             "code": "def insert(intervals, ni):\n    out = []; i = 0; n = len(intervals)\n    while i < n and intervals[i][1] < ni[0]:\n        out.append(intervals[i]); i += 1\n    while i < n and intervals[i][0] <= ni[1]:\n        ni = [min(ni[0], intervals[i][0]), max(ni[1], intervals[i][1])]; i += 1\n    out.append(ni)\n    while i < n: out.append(intervals[i]); i += 1\n    return out",
             "time": "O(n)", "space": "O(n)",
             "url": "https://leetcode.com/problems/insert-interval/"},
        ],
    },
    {
        "name": "Tries & Greedy",
        "blurb": "Prefix structures and locally-optimal moves.",
        "problems": [
            {"lc": 208, "name": "Implement Trie", "diff": "Medium",
             "approach": "Dict-of-dicts with end flag.",
             "code": "class Trie:\n    def __init__(self): self.root = {}\n    def insert(self, w):\n        n = self.root\n        for c in w: n = n.setdefault(c, {})\n        n['$'] = True\n    def search(self, w):\n        n = self.root\n        for c in w:\n            if c not in n: return False\n            n = n[c]\n        return '$' in n\n    def startsWith(self, p):\n        n = self.root\n        for c in p:\n            if c not in n: return False\n            n = n[c]\n        return True",
             "time": "O(L) per op", "space": "O(N*L)",
             "url": "https://leetcode.com/problems/implement-trie-prefix-tree/"},
            {"lc": 53, "name": "Maximum Subarray (Kadane)", "diff": "Medium",
             "approach": "Track best ending here vs. restart.",
             "code": "def maxSubArray(nums):\n    best = cur = nums[0]\n    for x in nums[1:]:\n        cur = max(x, cur + x); best = max(best, cur)\n    return best",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/maximum-subarray/"},
            {"lc": 55, "name": "Jump Game", "diff": "Medium",
             "approach": "Track furthest reachable.",
             "code": "def canJump(nums):\n    reach = 0\n    for i, x in enumerate(nums):\n        if i > reach: return False\n        reach = max(reach, i + x)\n    return True",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/jump-game/"},
            {"lc": 134, "name": "Gas Station", "diff": "Medium",
             "approach": "If total>=0, the answer exists. Reset start when running tank goes negative.",
             "code": "def canCompleteCircuit(gas, cost):\n    if sum(gas) < sum(cost): return -1\n    tank = start = 0\n    for i in range(len(gas)):\n        tank += gas[i] - cost[i]\n        if tank < 0: start = i + 1; tank = 0\n    return start",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/gas-station/"},
        ],
    },
    {
        "name": "Bit Manipulation",
        "blurb": "XOR tricks, masks, counting bits.",
        "problems": [
            {"lc": 136, "name": "Single Number", "diff": "Easy",
             "approach": "XOR all; pairs cancel.",
             "code": "def singleNumber(nums):\n    r = 0\n    for x in nums: r ^= x\n    return r",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/single-number/"},
            {"lc": 191, "name": "Number of 1 Bits", "diff": "Easy",
             "approach": "n &= n-1 trick.",
             "code": "def hammingWeight(n):\n    c = 0\n    while n: n &= n - 1; c += 1\n    return c",
             "time": "O(set bits)", "space": "O(1)",
             "url": "https://leetcode.com/problems/number-of-1-bits/"},
            {"lc": 268, "name": "Missing Number", "diff": "Easy",
             "approach": "XOR indices and values.",
             "code": "def missingNumber(nums):\n    r = len(nums)\n    for i, x in enumerate(nums): r ^= i ^ x\n    return r",
             "time": "O(n)", "space": "O(1)",
             "url": "https://leetcode.com/problems/missing-number/"},
            {"lc": 190, "name": "Reverse Bits", "diff": "Easy",
             "approach": "Build result bit-by-bit.",
             "code": "def reverseBits(n):\n    r = 0\n    for _ in range(32):\n        r = (r << 1) | (n & 1)\n        n >>= 1\n    return r",
             "time": "O(1) (32 bits)", "space": "O(1)",
             "url": "https://leetcode.com/problems/reverse-bits/"},
        ],
    },
    {
        "name": "Matrix",
        "blurb": "Grids, rotation, spiral.",
        "problems": [
            {"lc": 48, "name": "Rotate Image", "diff": "Medium",
             "approach": "Transpose + reverse each row.",
             "code": "def rotate(m):\n    n = len(m)\n    for i in range(n):\n        for j in range(i+1, n): m[i][j], m[j][i] = m[j][i], m[i][j]\n    for row in m: row.reverse()",
             "time": "O(n^2)", "space": "O(1)",
             "url": "https://leetcode.com/problems/rotate-image/"},
            {"lc": 54, "name": "Spiral Matrix", "diff": "Medium",
             "approach": "Maintain 4 bounds.",
             "code": "def spiralOrder(m):\n    if not m: return []\n    top, bot, lo, hi = 0, len(m)-1, 0, len(m[0])-1\n    out = []\n    while top <= bot and lo <= hi:\n        for c in range(lo, hi+1): out.append(m[top][c])\n        top += 1\n        for r in range(top, bot+1): out.append(m[r][hi])\n        hi -= 1\n        if top <= bot:\n            for c in range(hi, lo-1, -1): out.append(m[bot][c])\n            bot -= 1\n        if lo <= hi:\n            for r in range(bot, top-1, -1): out.append(m[r][lo])\n            lo += 1\n    return out",
             "time": "O(R*C)", "space": "O(1)",
             "url": "https://leetcode.com/problems/spiral-matrix/"},
            {"lc": 73, "name": "Set Matrix Zeroes", "diff": "Medium",
             "approach": "Use first row/col as markers; O(1) extra.",
             "code": "def setZeroes(m):\n    R, C = len(m), len(m[0])\n    fr = any(m[0][c] == 0 for c in range(C))\n    fc = any(m[r][0] == 0 for r in range(R))\n    for r in range(1, R):\n        for c in range(1, C):\n            if m[r][c] == 0: m[r][0] = m[0][c] = 0\n    for r in range(1, R):\n        for c in range(1, C):\n            if m[r][0] == 0 or m[0][c] == 0: m[r][c] = 0\n    if fr:\n        for c in range(C): m[0][c] = 0\n    if fc:\n        for r in range(R): m[r][0] = 0",
             "time": "O(R*C)", "space": "O(1)",
             "url": "https://leetcode.com/problems/set-matrix-zeroes/"},
        ],
    },
]


INDUSTRY_PROBLEMS: list[dict] = [
    {
        "name": "LRU Cache",
        "blurb": "Classic OS/system-design adjacent. Hashmap + doubly-linked list, both O(1).",
        "code": "class Node:\n    __slots__=('k','v','prev','nxt')\n    def __init__(self, k, v): self.k=k; self.v=v; self.prev=self.nxt=None\nclass LRUCache:\n    def __init__(self, cap):\n        self.cap = cap; self.mp = {}\n        self.head = Node(0,0); self.tail = Node(0,0)\n        self.head.nxt = self.tail; self.tail.prev = self.head\n    def _remove(self, n):\n        n.prev.nxt = n.nxt; n.nxt.prev = n.prev\n    def _push_front(self, n):\n        n.nxt = self.head.nxt; n.prev = self.head\n        self.head.nxt.prev = n; self.head.nxt = n\n    def get(self, k):\n        if k not in self.mp: return -1\n        n = self.mp[k]; self._remove(n); self._push_front(n)\n        return n.v\n    def put(self, k, v):\n        if k in self.mp:\n            n = self.mp[k]; n.v = v; self._remove(n); self._push_front(n)\n        else:\n            if len(self.mp) == self.cap:\n                lru = self.tail.prev; self._remove(lru); del self.mp[lru.k]\n            n = Node(k, v); self.mp[k] = n; self._push_front(n)",
    },
    {
        "name": "Token Bucket Rate Limiter",
        "blurb": "Allows bursts up to bucket size; refills at fixed rate. Common in API gateways.",
        "code": "import time\nclass TokenBucket:\n    def __init__(self, rate_per_sec, capacity):\n        self.rate = rate_per_sec; self.cap = capacity\n        self.tokens = capacity; self.last = time.monotonic()\n    def allow(self, n=1):\n        now = time.monotonic()\n        elapsed = now - self.last\n        self.tokens = min(self.cap, self.tokens + elapsed * self.rate)\n        self.last = now\n        if self.tokens >= n:\n            self.tokens -= n; return True\n        return False",
    },
    {
        "name": "LLM-Eval Pipeline with Judge Aggregation",
        "blurb": "Pure-Python sketch: each judge returns a (score, rationale); aggregate with median + agreement signal.",
        "code": "from statistics import median\nfrom collections import Counter\ndef aggregate_judgments(judgments):\n    # judgments: list of dicts {'score': int, 'verdict': 'pass'|'fail', 'rationale': str}\n    if not judgments: return {'score': None, 'verdict': None, 'agreement': 0.0}\n    scores = [j['score'] for j in judgments if isinstance(j.get('score'), (int, float))]\n    verdicts = Counter(j['verdict'] for j in judgments if j.get('verdict'))\n    top_verdict, top_count = verdicts.most_common(1)[0] if verdicts else (None, 0)\n    return {\n        'score': median(scores) if scores else None,\n        'verdict': top_verdict,\n        'agreement': top_count / len(judgments),\n        'rationales': [j.get('rationale', '') for j in judgments],\n    }",
    },
    {
        "name": "Hallucinated-API-Call Detection",
        "blurb": "Validate that an LLM-proposed tool call references real tools and required args before executing.",
        "code": "def validate_tool_call(call, tool_registry):\n    # call: {'name': str, 'arguments': dict}\n    # tool_registry: {name: {'required': [arg,...], 'optional': [...]}}\n    name = call.get('name')\n    if name not in tool_registry:\n        return False, f'unknown tool: {name}'\n    spec = tool_registry[name]\n    args = call.get('arguments') or {}\n    missing = [a for a in spec['required'] if a not in args]\n    if missing:\n        return False, f'missing required args: {missing}'\n    allowed = set(spec['required']) | set(spec.get('optional', []))\n    extra = [a for a in args if a not in allowed]\n    if extra:\n        return False, f'unknown args: {extra}'\n    return True, 'ok'",
    },
    {
        "name": "Exponential Backoff with Jitter",
        "blurb": "AWS-style decorrelated jitter — gentler on systems than pure exponential.",
        "code": "import random, time\ndef retry(fn, max_attempts=5, base=0.5, cap=10.0):\n    last_exc = None\n    sleep = base\n    for i in range(max_attempts):\n        try:\n            return fn()\n        except Exception as e:\n            last_exc = e\n            if i == max_attempts - 1: break\n            sleep = min(cap, random.uniform(base, sleep * 3))\n            time.sleep(sleep)\n    raise last_exc",
    },
]


AUTOMATION_QUESTIONS: list[dict] = [
    {"q": "Severity vs Priority — define and contrast.",
     "a": "Severity is the technical impact of a defect (does it crash, corrupt data, block a feature). Priority is the business urgency to fix it. They're independent: a typo on the homepage is low severity but high priority; a crash in a feature nobody uses might be high severity but low priority."},
    {"q": "Design a test framework from scratch — what layers?",
     "a": "Test runner + assertion lib at the bottom. Page Object / API Client abstraction layer above the driver. Test data factory. Config/env loader. Reporter (HTML + machine-readable). CI hooks. Test selection / tagging. Quarantine for flakes. Parallelization. Idempotent setup/teardown."},
    {"q": "A test passes locally but fails 1/20 in CI. Walk through your triage.",
     "a": "First: capture artifacts (logs, video, network HAR, DOM dump). Reproduce with the failing seed/order. Check for: timing assumptions, shared state, network nondeterminism, ordering dependencies between tests, resource leaks. Add structured logs, reduce to a minimal failing subset, then fix the root cause — never just add retries."},
    {"q": "Test pyramid — what does the shape mean and when does it break?",
     "a": "Many fast unit tests at the bottom, fewer integration in the middle, very few end-to-end at the top. Inverted (lots of E2E, few unit) means slow feedback, flakes, expensive maintenance. Breaks when the product is mostly orchestration (e.g., microservice routing) — then contract tests grow."},
    {"q": "API testing — what do you cover beyond status codes?",
     "a": "Schema validation, idempotency, auth/authz boundaries, error contract (codes + messages), rate limits, pagination correctness, partial failure semantics, latency budgets, backwards compatibility, observability (correlation IDs surface)."},
    {"q": "Mocks vs stubs vs fakes — when each?",
     "a": "Stubs return canned values. Mocks verify interactions (was this called with X). Fakes are working but simplified implementations (in-memory DB). Prefer fakes for collaborators you'd otherwise mock heavily; reach for mocks only when behavior under test is the call itself."},
    {"q": "CI is red. What's your first action?",
     "a": "Determine if it's the same as the last failure or new. If new: bisect commits, check infra status, look for flaky retry pattern. If same: triage the owner, decide hold/revert. Don't merge over red. Don't blanket-retry."},
    {"q": "How do you parallelize a slow suite without making it flaky?",
     "a": "Test isolation: each test owns its data (unique IDs, namespaces). No shared mutable resources (separate DBs, schemas, or transactions rolled back). Independent fixtures. Static analysis or runtime detection of cross-test state. Shard by historical duration."},
    {"q": "What does 'idempotent' mean in test/data terms — and why does it matter for retries?",
     "a": "Same input produces same effect no matter how many times you run it. Critical for safe retries: non-idempotent retries cause double charges, duplicated rows, etc. Use natural or client-supplied idempotency keys."},
    {"q": "Load test vs stress test vs soak test.",
     "a": "Load: expected peak traffic — verify SLOs. Stress: push past capacity to find the break point and degrade mode. Soak: sustained load for hours/days to surface leaks and slow degradation."},
    {"q": "How do you validate an LLM feature's quality in production?",
     "a": "Define the eval set with real examples + adversarial ones. Use a graded rubric (1-5 or pass/fail with categories). Mix human eval (gold) with judge-LLM eval (scale). Track drift over model/prompt changes. Sample live traffic with consent. Alert on regression — both quality and refusal rate."},
    {"q": "An intermittent hardware/system failure happens once every 10,000 runs. How do you root-cause it?",
     "a": "Add structured logging at every state transition. Snapshot environment (temp, voltage, firmware ver). Run a stress harness to bend the failure rate up. Bisect the variable space: which axis (input pattern, temperature, clock) correlates? Compare with a known-good system. Don't conclude until you can produce + suppress on demand."},
    {"q": "When do you write a UI test vs an API test for the same flow?",
     "a": "UI tests prove the surface — the contract a user sees — but they're slow and flaky. API tests cover logic. Generally: UI tests for one canonical happy path per critical flow, API tests for the matrix of variants and edge cases."},
    {"q": "What's a flaky test? How do you handle the inventory?",
     "a": "A test that passes and fails on the same code. Triage: quarantine (excluded from blocking signal but still run), file with a deadline, owner assigned. Track flake rate per test; expire long-quarantined tests rather than letting them rot."},
    {"q": "Contract testing — what problem does it solve?",
     "a": "In a multi-service world, integration tests are slow and flakey. Contract tests verify each service against a shared schema (provider + consumer), catching breaking changes before deploy. Pact, OpenAPI-based diff tools, etc."},
    {"q": "Code coverage — what's it good for and what's it not?",
     "a": "Good for: spotting un-tested code regions, regression checks, comparing PRs. Not good for: quality (you can have 100% coverage with terrible assertions). Don't chase a number; chase meaningful tests in risky areas."},
    {"q": "How do you test data pipelines / ETL?",
     "a": "Sample-based assertions on output schema, row counts, value distributions, key invariants (uniqueness, FK refs). Replay golden datasets. Backfill tests. Idempotency tests. Schema drift detection."},
    {"q": "How would you build a regression harness for an AI accelerator's silicon validation?",
     "a": "Tiered: directed tests for known features, constrained random for coverage, formal where tractable. Coverage model (functional, code, toggle). Reproducible seeds. Distributed run farm. Fail triage automation. Tight feedback to design via dashboards. Long-running soaks with thermal/voltage corners."},
]


BEHAVIORAL_STORIES: list[dict] = [
    {
        "title": "Why you left",
        "s": "After ~7 years on validation + SDET, I'd hit diminishing returns on the same architecture and saw the field shift toward generative + agentic systems.",
        "t": "Decide whether to keep optimizing inside or invest in a deliberate pivot before the market reset.",
        "a": "Took a clean break, enrolled in a postgrad in Generative & Agentic AI, capped a side project to ship one product end-to-end, set a hard application deadline.",
        "r": "Re-entering with a sharper portfolio — silicon-grade rigor applied to GenAI evaluation. Not a gap, a thesis.",
        "why": "Frames the break as a controlled investment with a defined exit, not drifting. Direct, no hedging.",
    },
    {
        "title": "Conflict — across teams",
        "s": "Validation engineering wanted feature freeze for stability; arch team wanted to land a late spec change for a customer.",
        "t": "Land both: protect quality without blocking a real revenue commitment.",
        "a": "Mapped the late change against current test coverage, proposed a phased scope (must-haves now, nice-to-haves next rev) with explicit risks costed in hours. Brought both sides one shared one-pager.",
        "r": "Customer commitment held; we shipped without a regression on the must-haves and deferred the rest cleanly. No grudges.",
        "why": "Shows you can disagree without making it personal, and that you negotiate with data.",
    },
    {
        "title": "Mentoring",
        "s": "Junior engineer was buried in flaky tests and reluctant to push back on test authors.",
        "t": "Get them to ship a debugged batch and a habit, not a fish.",
        "a": "Sat down once for the first triage, then made them lead the next three with me silent. Forced them to write the bug down in one sentence before opening any tool.",
        "r": "They closed eight flakes in two weeks and ran the next team-wide flake review. The habit transferred — that mattered more than the count.",
        "why": "Shows mentoring through enabling, not rescuing. Specific count + behavioral change.",
    },
    {
        "title": "Hardest technical challenge",
        "s": "A new accelerator failed sporadically under one workload — 1 in ~50,000 runs, no warning.",
        "t": "Find root cause without a reproducer, while the program timeline kept moving.",
        "a": "Built a stress harness that bent the failure rate up to ~1 in 200. Instrumented voltage + clock + temp telemetry. Bisected which axis correlated. Isolated to a clock-domain crossing in a specific workload shape. Repro on demand → fix → suppression confirmed.",
        "r": "Defect caught pre-tapeout; the harness became part of the standard validation pack.",
        "why": "The cycle 'bend the rate up, isolate, repro on demand, suppress' is the hireable story — not the specific bug.",
    },
    {
        "title": "Proudest project",
        "s": "Owned a validation pipeline that was a bottleneck for every release.",
        "t": "Get end-to-end ownership: design, parallelization, dashboards, on-call.",
        "a": "Re-architected to shard by historical runtime, added structured logs + a triage UI, paired with the DV team on flakes. Wrote the on-call runbook myself.",
        "r": "Median run dropped from ~9h to ~2h; on-call pages dropped >60%; the team adopted it as the default.",
        "why": "End-to-end ownership story with metrics. Avoid 'we' — own the pieces you actually owned.",
    },
    {
        "title": "Failure",
        "s": "Pushed for a test framework rewrite based on what I'd seen elsewhere.",
        "t": "Get the team onto a cleaner foundation.",
        "a": "Underweighted the cost of the migration on in-flight features. Two months in we'd doubled CI cost and had a half-migrated suite.",
        "r": "Paused, did the math honestly, rolled back to a more incremental approach. Lesson: a clean design only ships if the migration path is also clean. I now demand both before approving a rewrite.",
        "why": "Genuine failure with a structural lesson, not a humblebrag. Shows judgment improved.",
    },
    {
        "title": "Decision under incomplete information",
        "s": "Pre-tapeout: a new test was failing intermittently. Cause unknown. Tape-out window 72h.",
        "t": "Decide go/no-go on the feature.",
        "a": "Listed everything that would discriminate hardware bug vs test bug vs environment. Ran the four cheapest experiments in parallel. By hour 30 had enough signal that test + environment were the likely cause; flagged residual risk + a post-silicon experiment to confirm.",
        "r": "Shipped on time; the post-silicon experiment confirmed it was test-side; no field issue.",
        "why": "Shows comfort acting with uncertainty quantified, plus a follow-up plan. Calibrated, not cowboy.",
    },
]


RESOURCES: dict[str, list[dict]] = {
    "DSA": [
        {"name": "NeetCode", "url": "https://neetcode.io/", "why": "Roadmap + practice. Use the patterns view, not the linear list."},
        {"name": "NeetCode YouTube", "url": "https://www.youtube.com/@NeetCode", "why": "Walkthroughs after attempting — never before."},
        {"name": "Striver A2Z + SDE sheets", "url": "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/", "why": "Structured progression; good complement to NeetCode."},
        {"name": "Striver YouTube", "url": "https://www.youtube.com/@takeUforward", "why": "Detailed pattern teardowns."},
        {"name": "Abdul Bari Algorithms", "url": "https://www.youtube.com/@abdul_bari", "why": "When the fundamentals don't click. Slow, clear."},
        {"name": "LeetCode", "url": "https://leetcode.com/", "why": "The actual practice surface. Premium worth it the month before interviews."},
    ],
    "System Design": [
        {"name": "HelloInterview", "url": "https://www.hellointerview.com/", "why": "Mock interviews; system-design framework."},
        {"name": "ByteByteGo", "url": "https://bytebytego.com/", "why": "Alex Xu's visuals. Newsletter is free."},
        {"name": "Gaurav Sen YouTube", "url": "https://www.youtube.com/@gkcs", "why": "Trade-off thinking out loud."},
        {"name": "Hussein Nasser YouTube", "url": "https://www.youtube.com/@hnasr", "why": "Networking + DB internals."},
        {"name": "System Design Primer (GitHub)", "url": "https://github.com/donnemartin/system-design-primer", "why": "Free reference; use as scaffolding, not bible."},
    ],
    "Behavioral": [
        {"name": "Exponent", "url": "https://www.tryexponent.com/", "why": "Behavioral question banks; mocks for paid tier."},
        {"name": "Jeff H Sipe YouTube", "url": "https://www.youtube.com/@JeffHSipe-PracticeInterviews", "why": "Specific to Google; what bar raisers listen for."},
        {"name": "Dan Croitor YouTube", "url": "https://www.youtube.com/@DanCroitor", "why": "Amazon LP frameworks."},
    ],
    "Automation / SDET": [
        {"name": "Test Automation University", "url": "https://testautomationu.applitools.com/", "why": "Free courses across frameworks and languages."},
        {"name": "Naveen AutomationLabs YouTube", "url": "https://www.youtube.com/@naveenautomationlabs", "why": "Selenium/REST APIs from the ground up."},
        {"name": "Selenium docs", "url": "https://www.selenium.dev/documentation/", "why": "Reference, not tutorial."},
    ],
    "GenAI / ML": [
        {"name": "Karpathy 'Zero to Hero'", "url": "https://karpathy.ai/zero-to-hero.html", "why": "Build it up from scratch. Nothing better, free."},
        {"name": "3Blue1Brown", "url": "https://www.3blue1brown.com/", "why": "Intuition for the math."},
        {"name": "DeepLearning.AI short courses", "url": "https://www.deeplearning.ai/short-courses/", "why": "Free, short, applied — pick one matching your week's focus."},
        {"name": "Hugging Face Learn", "url": "https://huggingface.co/learn", "why": "Practical: agents, RAG, fine-tuning."},
    ],
    "Mock platforms": [
        {"name": "Pramp", "url": "https://www.pramp.com/", "why": "Free peer mocks. Variable signal — keep going."},
        {"name": "interviewing.io", "url": "https://interviewing.io/", "why": "Real engineers from real companies. Records sessions."},
        {"name": "Exponent mocks", "url": "https://www.tryexponent.com/mock-interviews", "why": "Paid; useful before a specific loop."},
    ],
}


COMPANY_GUIDES: dict[str, dict] = {
    "Google": {
        "process": [
            "Recruiter screen — usually a coding warm-up + targeting role/level.",
            "Technical phone screen (45m): one DSA, communicate clearly + complexity.",
            "Onsite / virtual onsite: 4–5 rounds. 2–3 coding, 1 systems/design (level-dependent), 1 behavioral / 'Googliness & Leadership'.",
            "Hiring committee review (anonymized packet of feedback).",
            "Team match / executive review for some levels.",
            "Offer + comp negotiation.",
        ],
        "rounds_score": [
            ("Coding", "Problem-solving, code quality, tests/edge cases, complexity, communication."),
            ("Systems / Design", "Requirements clarification, decomposition, trade-offs, depth on at least one component."),
            ("Behavioral / Googliness", "Collaboration, ambiguity, growth from setbacks, leadership-without-authority."),
        ],
        "level_bar": "L4 = ships features, owns project-sized scope. L5 = leads features end-to-end, drives technical direction, mentors. The system-design depth and behavioral leadership signal is what separates L5 from L4.",
        "real_questions": [
            "Robot Room Cleaner (LC489) — pathfinding without a known map.",
            "Word break / dictionary problems (variants).",
            "Design a chat system, design YouTube comments, design a typeahead service.",
            "'Tell me about a time you disagreed with your manager.'",
        ],
        "notes": "Process has shifted toward in-person final rounds for some teams in 2025. AI/ML topics now appear in non-AI roles' system-design rounds. Verify on careers.google.com/how-we-hire/ — it changes.",
    },
    "Amazon": {
        "process": [
            "Recruiter screen.",
            "Online assessment (some teams): timed DSA + work simulation + behavioral survey.",
            "Phone screen with hiring manager — coding + LPs.",
            "Loop (4–5 rounds): coding, system design (SDE II+), behavioral on LPs, Bar Raiser.",
            "Debrief; Bar Raiser has veto.",
            "Offer + comp.",
        ],
        "rounds_score": [
            ("Coding", "Bug-free, communicates clearly, tests."),
            ("System Design", "End-to-end, scale, trade-offs, ownership."),
            ("Behavioral (LP-based)", "STAR stories mapped to specific Leadership Principles."),
            ("Bar Raiser", "Cross-org check; raises the bar."),
        ],
        "level_bar": "SDE II = owns features. SDE III = owns systems and influences cross-team.",
        "real_questions": [
            "Design Amazon's order management.",
            "K closest points; LRU; trees.",
            "'Tell me about a time you had to make a decision with insufficient data.' (Bias for Action)",
        ],
        "notes": "Behavioral is half the loop. Memorize ~14 stories tagged to LPs. Use 'I' not 'we'.",
    },
    "Meta": {
        "process": [
            "Recruiter screen.",
            "Technical phone screen: 1 coding (sometimes 2 in 45 min).",
            "Onsite: 2 coding (~35m each, often 2 problems each), 1 design (E5+) or product architecture, 1 behavioral.",
            "Debrief; team match after offer.",
        ],
        "rounds_score": [
            ("Coding (Ninja)", "Tight: ~2 problems per 45m round. Speed + clean code."),
            ("Design", "Product systems (news feed, messaging, etc.). Trade-offs and metrics."),
            ("Behavioral (Jedi)", "Impact, collaboration, conflict, growth."),
        ],
        "level_bar": "E4 ships features. E5 owns systems and drives results across the team.",
        "real_questions": [
            "Random pick with weight (LC528).",
            "Subarray sum equals K (LC560).",
            "Verifying alien dictionary; valid parentheses.",
            "Design Instagram or Messenger.",
        ],
    },
    "Apple": {
        "process": [
            "Recruiter screen.",
            "Technical phone screens (often 2 — one DSA, one domain).",
            "Onsite: 4–6 rounds with future teammates and skip-level. Hardware-software boundary often surfaces.",
            "Team-specific; less standardized than Google/Amazon.",
        ],
        "rounds_score": [
            ("Coding", "Correctness + clarity; sometimes more applied/system."),
            ("Domain", "Deep dive on the team's area (silicon, OS, frameworks, etc.)."),
            ("Behavioral", "Craft, judgment, collaboration. Secrecy matters."),
        ],
        "level_bar": "ICT3 = strong individual contributor. ICT4 = leads area. ICT5+ = architect.",
        "real_questions": [
            "Walk through a time you owned silicon/firmware bring-up end to end.",
            "Memory-efficient string operations.",
            "Hardware-software interface design.",
        ],
    },
    "Netflix": {
        "process": [
            "Recruiter screen — senior-only bar.",
            "Hiring manager screen.",
            "Onsite: 4–5 rounds, deeply senior. Judgment + senior context heavily weighted.",
            "Comp is typically all-cash, top-of-market — but expect 'keeper test' culture.",
        ],
        "rounds_score": [
            ("Technical depth", "Real system experience, war stories."),
            ("Judgment", "Decisions with limited information; trade-offs."),
            ("Culture", "Direct feedback, dissent and commit, no-rules-rules alignment."),
        ],
        "level_bar": "Senior+ only typically. They want context for very senior decisions.",
    },
}


PREP_STRATEGY: dict = {
    "patterns": [
        ("sorted array, find pair", "Two Pointers"),
        ("k-th something", "Heap / Quickselect"),
        ("substring / window", "Sliding Window"),
        ("shortest path in unweighted graph or grid", "BFS"),
        ("shortest path in weighted graph (non-negative)", "Dijkstra"),
        ("count of ways / min steps to N", "1-D DP"),
        ("LIS / LCS / edit distance", "2-D DP"),
        ("dependencies / order", "Topological sort"),
        ("intervals / meetings", "Sort + sweep / heap"),
        ("connected components / cycles", "Union-Find or DFS"),
        ("all subsets / permutations / partitions", "Backtracking"),
        ("next greater / smaller", "Monotonic Stack"),
        ("prefix / range", "Prefix sum / segment tree"),
        ("repeated lookups by prefix", "Trie"),
        ("balanced parens / validity", "Stack"),
        ("LRU / O(1) ops on collection", "Hashmap + Doubly Linked List"),
    ],
    "retention": [
        "One template per pattern, memorized cold.",
        "Active recall: solve fresh; check; redo same problem 24h later from blank.",
        "Narrate aloud while coding. If you can't explain it, you don't own it.",
        "Spaced repetition: 1 day, 3 days, 7 days, 14 days.",
        "25-minute stuck rule: brainstorm 5 minutes, code 20. If still stuck, read the editorial — then redo from blank next day.",
        "Mock cadence: 1/week first month, 2/week second month, 3/week final two weeks.",
    ],
    "in_room_algo": [
        "Clarify input ranges, edges, output format. Ask 2-3 specific questions.",
        "Walk a concrete example end-to-end before coding.",
        "Propose approach + complexity. Get buy-in.",
        "Code while narrating: name variables, explain choices.",
        "Trace through your example. Catch one bug.",
        "State complexity and edge cases unprompted.",
    ],
}


JOB_BOARDS_NOTE = (
    "Verify comp ranges on Levels.fyi (https://www.levels.fyi/). "
    "Numbers vary by team, location, and negotiation; medians and 25th/75th percentiles "
    "are more honest than headline numbers."
)
